#!/bin/bash
echo "Enter a number "
read a 
echo "Enter a another number "
read b
sum= $(($a + $b))
substraction= $(($a - $b))
multiplication= $(($a * $b))
division= $(($a%$b))
echo "the sum of two numbers is" $sum
echo "the substraction of two numbers is" $substraction
echo $multiplication
echo $division
